### PR TITLE
Change JS project into a TypeScript project

### PR DESCRIPTION
**Pull request by dohomi**
Hello 

I took some initiative to create this project into a TypeScript project which enables the renderer to be used inside of TS projects and generates typings out of the box.
I chose `microbundle` to compile to JS.

There is one breaking change, thats the NODE_RESOLVERS and MARK_RESOLVERS, these types are now of type enum and thus the README would need a very minor adjustment to clarify that.

Let me know what you think about this changes

### CODE REVIEW

**Comment by claus** [comment]
Hey @dohomi, thanks for your PR!

I'm not much of a TypeScript guy, i really prefer vanilla JS, especially for a tiny project like this. What i thought might be helpful for people consuming this in a TypeScript project is providing a `.d.ts` so they have type information available.

Can we reuse things from this PR and put them in a `.d.ts`?

**Comment by dohomi** [comment]
Hello @claus 
I am not much of a JavaScript guy to know how to get a `.d.ts` out of a vanilla JS file. I guess that would need an entire different approach, probably writing the typings by hand. 
I can leave the fork up for people who might be interested or I just leave it parallel and we kind of sync our projects every time there are changes made in Storyblok (which I don't think will be frequent)

**Comment by claus** [comment]
@dohomi Can't the `index.d.ts` that your project generates be used? It's virtually identical to the first 43 lines of your `index.ts`, with only `declare` keywords added.

**Comment by dohomi** [comment]
@claus the index.d.ts only exists because I replaced your index.js => index.ts file and then run the build script (microbundle). So basically if you would cherry pick the *.d.ts file out of this PR its a one time thing and you can use it now in your project but later on if you make changes you need to manually adjust the changes back to the typings file

**Comment by claus** [comment]
Yes i'm aware that the `index.d.ts` has to be maintained

**Comment by dohomi** [comment]
sure you can use it

**Comment by darkowic** [comment]
This is great! I already use the beta package and works perfectly! At least for my first try. Types are there. Just one note: options should not be required.

:ship: it :)

**Comment by dohomi** [comment]
@darkowic you will find a ts version of this project here: https://github.com/dohomi/storyblok-rich-text-react-renderer-ts (current v3.0.2)

**Comment by selrond** [comment]
@dohomi @claus what's the current state of this?

**Comment by dohomi** [comment]
@selrond both packages are still actively maintained. If you need typings then the `-ts` version might be better for you (https://github.com/claus/storyblok-rich-text-react-renderer/pull/5#issuecomment-748700907)

**Comment by claus** [comment]
The `-ts` package is a bit behind this package though. It currently doesn't support [plain `string` input](https://github.com/claus/storyblok-rich-text-react-renderer/commit/17afefe1afe5bc58bdaece798ae83174fc876de0) and [linked images](https://github.com/claus/storyblok-rich-text-react-renderer/commit/189811ccf95d5dd154b02ebac929a03729754b51).

**Comment by selrond** [comment]
@claus so you don't plan to have TS support?

**Comment by claus** [comment]
@selrond If someone could contribute a `.d.ts` that would be awesome.

**Comment by selrond** [comment]
@dohomi I found [this](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) which might help a bit. 

Are you still interested in writing the types?

**Comment by dohomi** [comment]
@selrond I realised that the easiest is  to transform this small package into TS, that was my intention with this PR. I am happy to keep both packages side-by-side.
Thanks @claus for pointing to the two additions, I never had a need of them but will add them sometimes soon as well

**Comment by dohomi** [comment]
I added the last additions to the TS version and released 3.1.1

**Comment by selrond** [comment]
@dohomi do you think this is sustainable?

**Comment by dohomi** [comment]
@selrond not sure what you mean? I use only NextJS + TypeScript + Storyblok thats why I forked this package. I did not find a reliable way of receiving typings based on JS files so I rewrote the JS files to TS files and use `microbundle` to generate the esm/umd bundles. the "-ts" package will live as long there are no typings in this renderer, feel free to create a new PR to include them inside of this package- I would deprecate mine because the credits of the renderer are all going to @claus

**Comment by selrond** [comment]
I just mean keeping things in sync manually

**Comment by selrond** [comment]
even now, as I try to use your package, `storyblok-rich-text-react-renderer-ts` is not exporting element types, but the README says otherwise. So it's not even compatible with the original project

**Comment by dohomi** [comment]
@selrond then this an issue on that repo not this one. I released a new version and added the missing types. If you find issues with typings you can create an issue there. Because the fork is re-written in TS its not identical

**Pull request closed without merging**
